# Generated by Django 3.0 on 2022-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.ImageField(upload_to='')),
                ('ename', models.CharField(max_length=50)),
                ('salary', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
